name: Deploy via ftp
on:
  pull_request_review:
    types: [submitted]
jobs:
  approved:
    if: github.event.review.state == 'approved'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          password: ${{secrets.PASS}}
          remoteDir: ${{secrets.WORK_DIR}}
